@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json

###

@name=blog
@id=5c50094ab45fe9411c3aae89

PUT http://{{host}}/bloglist/0 HTTP/1.1
Content-Type: {{contentType}}

{
    "title": "测"
}

###

GET  http://{{host}}/{{name}}/{{id}}/manage HTTP/1.1

###

POST http://{{host}}/{{name}} HTTP/1.1
Content-Type: {{contentType}}

{
    "title": "Hello world3",
    "category": "文章",
    "tags": ["javascript","react"],
    "content": "# personal-site-service\n\nBack-end service for personal site."
}

###

PUT http://{{host}}/{{name}}/{{id}} HTTP/1.1
Content-Type: {{contentType}}

{
    "content": "# personal-site\n\nBackup for my personal site."
}

###

DELETE http://{{host}}/{{name}}/{{id}} HTTP/1.1
